/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficosEstudiante;

import com.java4read.modelo.Pregunta;
import com.java4read.modelo.PreguntaMultiple;
import com.java4read.modelo.Prueba;
import controladorestudiante.ExamenControladorE;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;


/**
 *
 * @author gianlucasorem
 */
public class InicioEstudiante extends javax.swing.JFrame {
    
    PreguntaMultipleG preguntamult = new PreguntaMultipleG();
    int x=0;
    
    
    PreguntaAbierta abierta = new PreguntaAbierta();
    CardLayout vista;
    List<Pregunta> preguntaspiloto;
    String descripcionpiloto;
    Prueba pruebapiloto=new Prueba(preguntaspiloto);

    /**
     * Creates new form InicioEstudiante
     */
    public InicioEstudiante() {
        initComponents();
        
        
       // selMultiple1.setProfe(this);
        setLocationRelativeTo(null);
        vista = (CardLayout) Pnl_principal.getLayout();
    }
    
    
   
    
    
    public void cambiarTarjeta(String Cadena,Object c){
        System.out.println("Entro");
        Pnl_principal.add((Component) c, Cadena);
        vista.show(Pnl_principal, Cadena);
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Pnl_principal = new javax.swing.JPanel();
        panelInicioE1 = new graficosEstudiante.PanelInicioE();
        preguntaAbierta1 = new graficosEstudiante.PreguntaAbierta();
        preguntaMultipleG1 = new graficosEstudiante.PreguntaMultipleG();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Realizar Examen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Subir Examen");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jButton1)
                .addGap(165, 165, 165)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pnl_principal.setBackground(new java.awt.Color(255, 255, 255));
        Pnl_principal.setLayout(new java.awt.CardLayout());
        Pnl_principal.add(panelInicioE1, "card4");
        Pnl_principal.add(preguntaAbierta1, "card3");
        Pnl_principal.add(preguntaMultipleG1, "card4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pnl_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*Pnl_principal.add(selmultiple, "selmultiple");
        vista.show(Pnl_principal, "selmultiple");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        */
        Pregunta pregunta;
        PreguntaMultiple pregunta2;
        pruebapiloto=ExamenControladorE.getInstance().guardarPruebaDesdeArchivo();
        preguntaspiloto=pruebapiloto.getPreguntas();
        descripcionpiloto=pruebapiloto.getDescripcion();
        String[] respuestasmostrar=new String[4];
        Boolean[] respuestas_correctas=new Boolean[4];
        int porcentaje;
        int i=0;
        
        System.out.println("hola "+preguntaspiloto.size());
        
        
        
        while (i<preguntaspiloto.size()){
            System.out.println("hola2");
            System.out.println(preguntaspiloto.get(i));
            
            if(preguntaspiloto.get(i) instanceof PreguntaMultiple)
            {
                pregunta2=(PreguntaMultiple) preguntaspiloto.get(i);
                String enunciadopil=pregunta2.getEnunciado();
                respuestasmostrar=pregunta2.getRespuestas();
                respuestas_correctas=pregunta2.getSolucion();
                porcentaje=pregunta2.getPorcentaje();
                System.out.println(respuestas_correctas[0]);
                
                
                preguntamult.agregarInfo(enunciadopil,respuestasmostrar);
                
                  
                
                cambiarTarjeta("Multiple",preguntamult);
                
                ExamenControladorE.getInstance().obtenerRespuestasProfesor(respuestas_correctas, porcentaje);
                
                
               
                
                
                i=i+1;
                
            
            }
            
            
            else if(preguntaspiloto.get(i) instanceof Pregunta)
            {
                pregunta= preguntaspiloto.get(i);
                String enunciadopil=pregunta.getEnunciado();
                abierta.agregarInfo(enunciadopil);
                
                cambiarTarjeta("Abierta",abierta);
            
            
            i=i+1;
            
            
            }
        }
    
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
   ExamenControladorE.getInstance().subirRespuestasArch();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pnl_principal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private graficosEstudiante.PanelInicioE panelInicioE1;
    private graficosEstudiante.PreguntaAbierta preguntaAbierta1;
    private graficosEstudiante.PreguntaMultipleG preguntaMultipleG1;
    // End of variables declaration//GEN-END:variables
}
